apiVersion: v1
kind: Service
metadata:
  name: snu-anomaly-loadbalancer
  namespace: space-openess
  annotations:
    loxilb.io/liveness: "yes"
    loxilb.io/lbmode: "onearm"
spec:
  externalTrafficPolicy: Local
  selector:
    serving.kserve.io/inferenceservice: snu-anomaly
  ports:
    - protocol: TCP
      port: 59202
      targetPort: 8082 # Replace with the port your predictor is running on
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerClass: loxilb.io/loxilb
